name: Test project
on: [push]
jobs:
  testProj:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  
    - name: Ensure project runs
      run: |
        pip install -r requirements.txt; cd ./src; (python main.py)
    - run: echo "üçè This job's status is ${{ job.status }}."
  